# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb3767a7cd2ac4599450716dd14b384a7b8007c773352578c4d016d01528ddb355a85ab81186f8c9842abe753c14cdac553a976ddb9231f070592527f073f1a7

test:
  secret_key_base: 7eb09e5b07f1974f21ce84e36283e8dc06f2a268bf5b9a4689c9267dc072bb981e675c931fe45e079f6f7961944fed513517bc5af4e4b2638c72a6e32a434ca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
